# Generated by Django 5.1.2 on 2024-10-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_visible',
        ),
    ]
