# Generated by Django 5.1.2 on 2024-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_reservation_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
