# Generated by Django 5.1.2 on 2024-10-20 17:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_reservation_is_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(default='lol', max_length=80)),
                ('item_description', ckeditor.fields.RichTextField(default='lol')),
                ('item_icon', models.CharField(default='lol', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
