# Generated by Django 5.1.2 on 2024-10-20 17:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_footeritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeritem',
            name='item_description',
            field=ckeditor.fields.RichTextField(blank=True, default='lol', null=True),
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='item_icon',
            field=models.CharField(blank=True, default='lol', max_length=250, null=True),
        ),
    ]
